#pragma once
#include <JuceHeader.h>

class SimpleSound : public juce::SynthesiserSound
{
public:
    bool appliesToNote (int) override { return true; }
    bool appliesToChannel (int) override { return true; }
};

class BandLimitedOscillator
{
public:
    void prepare (double newSampleRate)
    {
        sampleRate = juce::jmax (1.0, newSampleRate);
        reset();
    }

    void reset (double newPhase = 0.0)
    {
        phase = newPhase - std::floor (newPhase);
        triangleState = 0.0f;
        dcX1 = dcY1 = 0.0f;
    }

    void setFrequency (float newFrequency)
    {
        frequency = juce::jlimit (0.0f, static_cast<float> (sampleRate * 0.45), newFrequency);
        phaseIncrement = static_cast<double> (frequency) / sampleRate;
    }

    void setWaveform (int newWaveform) { waveform = juce::jlimit (0, 3, newWaveform); }

    float process()
    {
        const double t = phase;
        const double dt = juce::jmax (phaseIncrement, 1.0e-9);
        float output = 0.0f;

        switch (waveform)
        {
            case 1: // Band-limited saw
            {
                output = static_cast<float> (2.0 * t - 1.0 - polyBlep (t, dt));
                break;
            }

            case 2: // Band-limited square
            {
                output = squareAt (t, dt);
                break;
            }

            case 3: // Triangle generated by integrating a band-limited square
            {
                const float square = squareAt (t, dt);
                triangleState += square * static_cast<float> (4.0 * dt);
                triangleState = juce::jlimit (-1.2f, 1.2f, triangleState);

                // Gentle DC blocker keeps the integrated waveform centred without colouring it heavily.
                const float y = triangleState - dcX1 + 0.995f * dcY1;
                dcX1 = triangleState;
                dcY1 = y;
                output = juce::jlimit (-1.0f, 1.0f, y);
                break;
            }

            default: // Sine is naturally band-limited
                output = std::sin (static_cast<float> (juce::MathConstants<double>::twoPi * t));
                break;
        }

        phase += phaseIncrement;
        phase -= std::floor (phase);
        return output;
    }

private:
    static double polyBlep (double t, double dt)
    {
        if (t < dt)
        {
            t /= dt;
            return t + t - t * t - 1.0;
        }

        if (t > 1.0 - dt)
        {
            t = (t - 1.0) / dt;
            return t * t + t + t + 1.0;
        }

        return 0.0;
    }

    static float squareAt (double t, double dt)
    {
        double value = t < 0.5 ? 1.0 : -1.0;
        value += polyBlep (t, dt);

        double shifted = t + 0.5;
        if (shifted >= 1.0)
            shifted -= 1.0;

        value -= polyBlep (shifted, dt);
        return static_cast<float> (value);
    }

    double sampleRate = 44100.0;
    double phase = 0.0;
    double phaseIncrement = 440.0 / 44100.0;
    float frequency = 440.0f;
    int waveform = 0;

    float triangleState = 0.0f;
    float dcX1 = 0.0f, dcY1 = 0.0f;
};

class SynthVoice : public juce::SynthesiserVoice
{
public:
    explicit SynthVoice (juce::AudioProcessorValueTreeState& state);

    bool canPlaySound (juce::SynthesiserSound* sound) override;
    void startNote (int midiNoteNumber, float velocity, juce::SynthesiserSound*, int) override;
    void stopNote (float velocity, bool allowTailOff) override;
    void pitchWheelMoved (int) override {}
    void controllerMoved (int, int) override {}
    void prepare (double sampleRate, int samplesPerBlock, int outputChannels);
    void renderNextBlock (juce::AudioBuffer<float>& outputBuffer, int startSample, int numSamples) override;

private:
    juce::AudioProcessorValueTreeState& apvts;
    BandLimitedOscillator osc1, osc2;
    juce::dsp::StateVariableTPTFilter<float> filter;
    juce::ADSR ampEnvelope;
    juce::ADSR::Parameters adsrParams;

    double currentSampleRate = 44100.0;
    float baseFrequency = 440.0f;
    float noteVelocity = 1.0f;

    void updateOscillatorWaveforms();
    void updateEnvelope();
    void updateFrequencies();
};
